### ISSUE TITLE
Crash when creating a Command Template for a renamed OSC module

### ISSUE THREAD

**Issue by tommag** [benkuper/Chataigne#26]
Hello, 
I get a segfault crash when I try to create a Command Template for OSC modules that have been renamed. 

Steps to reproduce : 
* create an OSC module
* rename it
* create a Command Template

It only happens for OSC modules, and only after they have been renamed. 

Backtrace : 

> #0  0x000055555572f930 in juce::HeapBlock<CommandDefinition*, false>::operator CommandDefinition** (this=0x668)
>     at /home/tom/JUCE/modules/juce_core/memory/juce_HeapBlock.h:155
> #1  0x00005555557321a0 in juce::OwnedArray<CommandDefinition, juce::DummyCriticalSection>::begin (this=0x668)
>     at /home/tom/JUCE/modules/juce_core/containers/juce_OwnedArray.h:218
> #2  0x0000555555956ebd in Module::getCommands (this=0x0, includeTemplateCommands=false)
>     at ../../Source/Module/Module.cpp:95
> #3  0x000055555572d6a3 in CommandTemplate::CommandTemplate (this=0x555556d59170, params=...)
>     at ../../Source/Common/Command/Template/CommandTemplate.cpp:47
> #4  0x0000555555731750 in CommandTemplate::create (params=...)
>     at ../../Source/Common/Command/Template/CommandTemplate.h:60
> #5  0x0000555555733487 in std::_Function_handler<CommandTemplate* (juce::var), CommandTemplate* (*)(juce::var)>::_M_invoke(std::_Any_data const&, juce::var&&) (__functor=..., __args#0=...)
>     at /usr/include/c++/8.1.1/bits/std_function.h:282
> #6  0x0000555555723fff in std::function<CommandTemplate* (juce::var)>::operator()(juce::var) const (
>     this=0x555556d305f0, __args#0=...) at /usr/include/c++/8.1.1/bits/std_function.h:687
> #7  0x0000555555722b9d in Factory<CommandTemplate>::create (this=0x555556d136d8, type=...)
>     at ../../../JUCE Modules/juce_organicui/manager/Factory.h:122
> #8  0x000055555572142e in Factory<CommandTemplate>::createFromMenuResult (this=0x555556d136d8, result=1)
>     at ../../../JUCE Modules/juce_organicui/manager/Factory.h:113
> #9  0x000055555571fd8a in Factory<CommandTemplate>::showCreateMenu (this=0x555556d136d8)
>     at ../../../JUCE Modules/juce_organicui/manager/Factory.h:98
> #10 0x000055555571cf22 in BaseManagerUI<CommandTemplateManager, CommandTemplate, BaseItemUI<CommandTemplate> >::showMenuAndAddItem (this=0x555556d324f0, isFromAddButton=true, mouseDownPos=...)
>     at ../../../JUCE Modules/juce_organicui/manager/ui/BaseManagerUI.h:524
> #11 0x000055555571de04 in BaseManagerUI<CommandTemplateManager, CommandTemplate, BaseItemUI<CommandTemplate> >::buttonClicked (this=0x555556d324f0, b=0x555556d36f50)
>     at ../../../JUCE Modules/juce_organicui/manager/ui/BaseManagerUI.h:743
> #12 0x0000555555dbcfd9 in juce::Button::<lambda(juce::Button::Listener&)>::operator()(juce::Button::Listener &) const (__closure=0x7fffffffd790, l=...) at /home/tom/JUCE/modules/juce_gui_basics/buttons/juce_Button.cpp:402
> #13 0x0000555555e5857a in juce::ListenerList<juce::Button::Listener, juce::Array<juce::Button::Listener*, juce::DummyCriticalSection, 0> >::callChecked<juce::Button::sendClickMessage(const juce::ModifierKeys&)::<lambda(juce::Button::Listener&)>, juce::Component::BailOutChecker>(const juce::Component::BailOutChecker &, juce::Button::<lambda(juce::Button::Listener&)> &&) (this=0x555556d37098, bailOutChecker=..., callback=...)
>     at /home/tom/JUCE/modules/juce_core/containers/juce_ListenerList.h:153
> #14 0x0000555555dbd0dc in juce::Button::sendClickMessage (this=0x555556d36f50, modifiers=...)
>     at /home/tom/JUCE/modules/juce_gui_basics/buttons/juce_Button.cpp:402
> #15 0x0000555555dbce86 in juce::Button::internalClickCallback (this=0x555556d36f50, modifiers=...)
>     at /home/tom/JUCE/modules/juce_gui_basics/buttons/juce_Button.cpp:351
> #16 0x0000555555dbd526 in juce::Button::mouseUp (this=0x555556d36f50, e=...)
>     at /home/tom/JUCE/modules/juce_gui_basics/buttons/juce_Button.cpp:471
> #17 0x0000555555db19d8 in juce::Component::internalMouseUp (this=0x555556d36f50, source=..., relativePos=..., 
>     time=..., oldModifiers=..., pressure=0, orientation=0, rotation=0, tiltX=0, tiltY=0)
>     at /home/tom/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:2383
> #18 0x0000555555e691de in juce::MouseInputSourceInternal::sendMouseUp (this=0x555556b04c50, comp=..., 
>     screenPos=..., time=..., oldMods=...)
>     at /home/tom/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:155
> ---Type <return> to continue, or q <return> to quit---
> #19 0x0000555555e69660 in juce::MouseInputSourceInternal::setButtons (this=0x555556b04c50, screenPos=..., 
>     time=..., newButtonState=...) at /home/tom/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:197
> #20 0x0000555555e6a265 in juce::MouseInputSourceInternal::handleEvent (this=0x555556b04c50, newPeer=..., 
>     positionWithinPeer=..., time=..., newMods=..., newPressure=0, newOrientation=0, pen=...)
>     at /home/tom/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:331
> #21 0x0000555555db4a09 in juce::MouseInputSource::handleEvent (this=0x7fffffffdc30, peer=..., pos=..., 
>     time=1529315697282, mods=..., pressure=0, orientation=0, penDetails=...)
>     at /home/tom/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:631
> #22 0x0000555555e42232 in juce::ComponentPeer::handleMouseEvent (this=0x555556b3e0f0, 
>     type=juce::MouseInputSource::mouse, pos=..., newMods=..., newPressure=0, newOrientation=0, 
>     time=1529315697282, pen=..., touchIndex=0)
>     at /home/tom/JUCE/modules/juce_gui_basics/windows/juce_ComponentPeer.cpp:88
> #23 0x0000555555ea9ceb in juce::LinuxComponentPeer::handleButtonReleaseEvent (this=0x555556b3e0f0, 
>     buttonRelEvent=...) at /home/tom/JUCE/modules/juce_gui_basics/native/juce_linux_X11_Windowing.cpp:2292
> #24 0x0000555555ea8e76 in juce::LinuxComponentPeer::handleWindowMessage (this=0x555556b3e0f0, event=...)
>     at /home/tom/JUCE/modules/juce_gui_basics/native/juce_linux_X11_Windowing.cpp:2018
> #25 0x0000555555e54bb5 in juce::WindowingHelpers::windowMessageReceive (event=...)
>     at /home/tom/JUCE/modules/juce_gui_basics/native/juce_linux_X11_Windowing.cpp:3775
> #26 0x0000555555e52c6e in juce::XWindowSystem::<lambda(int)>::operator()(int) const (__closure=0x555556b61fc0)
>     at /home/tom/JUCE/modules/juce_gui_basics/native/juce_linux_X11.cpp:217
> #27 0x0000555555e63fd4 in juce::LinuxEventLoop::CallbackFunction<juce::XWindowSystem::initialiseXDisplay()::<lambda(int)> >::operator()(int) (this=0x555556b61fb0, fd=6)
>     at /home/tom/JUCE/modules/juce_events/native/juce_linux_EventLoop.h:42
> #28 0x0000555555cbcd13 in juce::InternalMessageQueue::dispatchNextEvent (this=0x555556b03e50)
>     at /home/tom/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:121
> #29 0x0000555555cb9c90 in juce::MessageManager::dispatchNextMessageOnSystemQueue (
>     returnIfNoPendingMessages=false) at /home/tom/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:237
> #30 0x0000555555cb5b8b in juce::MessageManager::runDispatchLoop (this=0x555556b03de0)
>     at /home/tom/JUCE/modules/juce_events/messages/juce_MessageManager.cpp:128
> #31 0x0000555555cb4fee in juce::JUCEApplicationBase::main ()
>     at /home/tom/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:262
> #32 0x0000555555cb4ef0 in juce::JUCEApplicationBase::main (argc=1, argv=0x7fffffffe058)
>     at /home/tom/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:240
> #33 0x0000555555a97e23 in main (argc=1, argv=0x7fffffffe058) at ../../Source/Main.h:36

**Comment by tommag** [comment]
As a workaround : Chataigne doesn't crash if the renamed OSC module is loaded from file. 
e.g. create OSC module ; rename it ; save file ; restart Chataigne ; load file ; create command template does not crash.

**Comment by tommag** [comment]
:thumbsup:
